# Set prefix to Ctrl-a (instead of Ctrl-b)
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Enable mouse support (scrolling, resizing, clicking)
set -g mouse on

# Start window and pane numbering at 1
set -g base-index 1
setw -g pane-base-index 1

# Faster command sequences
set -sg escape-time 0

# Increase history limit
set -g history-limit 50000

# Vim keys for copy mode
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"

# Splitting panes (intuitive)
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# Reload tmux config
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"

# Set the plugin manager path so the bootstrap script doesn't fail
set-environment -g TMUX_PLUGIN_MANAGER_PATH "~/.tmux/plugins"

# Plugins (Managed by TPM)
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-vim-focus' # Resizes panes when vim opens
set -g @plugin 'christoomey/vim-tmux-navigator' # Seamless vim/tmux pane navigation

# Initialize TMUX plugin manager (keep this line at the very bottom)
run '~/.tmux/plugins/tpm/bin/tpm'
